### PR TITLE
Add a method to return details for an nzb

### PR DESCRIPTION
**Pull request by lsnow99**
Return details for an item, per [newznab specification](https://newznab.readthedocs.io/en/latest/misc/api/#details).

### CODE REVIEW

**Comment by mrobinsn** [comment]
Thanks for this @lsnow99. Would you mind merging master back into this branch and pushing that up?

I replaced the old travis-ci setup with a new one so we can check the test results for this PR.

**Comment by lsnow99** [comment]
Sure thing, I can do that when I get off work. I should also probably add a unit test, I'll look to see how you are handling those.

**Comment by lsnow99** [comment]
Hey @mrobinsn lmk how it looks now

**Review by mrobinsn — APPROVED** [review]
LGTM

**Comment by mrobinsn** [comment]
Thanks @lsnow99, this has been included in the [v1.2.0](https://github.com/mrobinsn/go-newznab/releases/tag/v1.2.0) release

**Comment by lsnow99** [comment]
Awesome thank you!

**Pull request merged**
